// Code generated by protoc-gen-gogo.
// source: trade.proto
// DO NOT EDIT!

package models

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Trade struct {
	Ram                *int64  `protobuf:"varint,4,req,name=Ram" json:"Ram,omitempty"`
	Cpu                *int64  `protobuf:"varint,5,req,name=Cpu" json:"Cpu,omitempty"`
	Gpu                *int64  `protobuf:"varint,6,req,name=Gpu" json:"Gpu,omitempty"`
	TradeId            *string `protobuf:"bytes,1,req,name=TradeId" json:"TradeId,omitempty"`
	Ticker             *string `protobuf:"bytes,2,req,name=Ticker" json:"Ticker,omitempty"`
	Provider           *string `protobuf:"bytes,3,req,name=Provider" json:"Provider,omitempty"`
	Side               *string `protobuf:"bytes,7,req,name=Side" json:"Side,omitempty"`
	ResourceInstanceID *string `protobuf:"bytes,8,req,name=ResourceInstanceID" json:"ResourceInstanceID,omitempty"`
	ID                 *uint32 `protobuf:"varint,9,opt,name=ID" json:"ID,omitempty"`
	CreatedAt          *int64  `protobuf:"varint,10,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	DeletedAt          *int64  `protobuf:"varint,11,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}

func (m *Trade) GetRam() int64 {
	if m != nil && m.Ram != nil {
		return *m.Ram
	}
	return 0
}

func (m *Trade) GetCpu() int64 {
	if m != nil && m.Cpu != nil {
		return *m.Cpu
	}
	return 0
}

func (m *Trade) GetGpu() int64 {
	if m != nil && m.Gpu != nil {
		return *m.Gpu
	}
	return 0
}

func (m *Trade) GetTradeId() string {
	if m != nil && m.TradeId != nil {
		return *m.TradeId
	}
	return ""
}

func (m *Trade) GetTicker() string {
	if m != nil && m.Ticker != nil {
		return *m.Ticker
	}
	return ""
}

func (m *Trade) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

func (m *Trade) GetSide() string {
	if m != nil && m.Side != nil {
		return *m.Side
	}
	return ""
}

func (m *Trade) GetResourceInstanceID() string {
	if m != nil && m.ResourceInstanceID != nil {
		return *m.ResourceInstanceID
	}
	return ""
}

func (m *Trade) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Trade) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Trade) GetDeletedAt() int64 {
	if m != nil && m.DeletedAt != nil {
		return *m.DeletedAt
	}
	return 0
}

type Leger struct {
	ID               *uint32 `protobuf:"varint,5,opt,name=ID" json:"ID,omitempty"`
	BuyerTradeID     *string `protobuf:"bytes,1,req,name=BuyerTradeID" json:"BuyerTradeID,omitempty"`
	SellerTradeID    *string `protobuf:"bytes,2,req,name=SellerTradeID" json:"SellerTradeID,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,3,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	DeletedAt        *int64  `protobuf:"varint,4,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Leger) Reset()         { *m = Leger{} }
func (m *Leger) String() string { return proto.CompactTextString(m) }
func (*Leger) ProtoMessage()    {}

func (m *Leger) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Leger) GetBuyerTradeID() string {
	if m != nil && m.BuyerTradeID != nil {
		return *m.BuyerTradeID
	}
	return ""
}

func (m *Leger) GetSellerTradeID() string {
	if m != nil && m.SellerTradeID != nil {
		return *m.SellerTradeID
	}
	return ""
}

func (m *Leger) GetCreatedAt() int64 {
	if m != nil && m.CreatedAt != nil {
		return *m.CreatedAt
	}
	return 0
}

func (m *Leger) GetDeletedAt() int64 {
	if m != nil && m.DeletedAt != nil {
		return *m.DeletedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Trade)(nil), "models.Trade")
	proto.RegisterType((*Leger)(nil), "models.Leger")
}
